=== CostaHiripis/dataProcessing/src/main/resources/schema/agriculture/agriculture_schema.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="https://www.w3schools.com"
           elementFormDefault="qualified"
           xmlns="https://www.w3schools.com">

    <xs:element name="agriculture">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="areaCode" type="xs:int"/>
                <xs:element name="area" type="xs:string"/>
                <xs:element name="itemCode" type="xs:int"/>
                <xs:element name="item" type="xs:string"/>
                <xs:element name="elementCode" type="xs:int"/>
                <xs:element name="element" type="xs:string"/>
                <xs:element name="year" type="year"/>
                <xs:element name="unit" type="unit"/>
                <xs:element name="value" type="xs:long"/>
                <xs:element name="flag" type="flag"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="unit">
        <xs:restriction base="xs:string">
            <xs:enumeration value="0.1g/An"/>
            <xs:enumeration value="1000 Head"/>
            <xs:enumeration value="1000 No"/>
            <xs:enumeration value="100mg/An"/>
            <xs:enumeration value="ha"/>
            <xs:enumeration value="Head"/>
            <xs:enumeration value="hg"/>
            <xs:enumeration value="hg/An"/>
            <xs:enumeration value="hg/ha"/>
            <xs:enumeration value="No"/>
            <xs:enumeration value="No/An"/>
            <xs:enumeration value="tonnes"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="flag">
        <xs:restriction base="xs:string">
            <xs:enumeration value="*"/>
            <xs:enumeration value="A"/>
            <xs:enumeration value="F"/>
            <xs:enumeration value="Fc"/>
            <xs:enumeration value="lm"/>
            <xs:enumeration value="M"/>
            <xs:enumeration value="R"/>
            <xs:enumeration value=""/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="year">
        <xs:restriction base="xs:int">
            <xs:minInclusive value="1900"/>
            <xs:maxInclusive value="2020"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== CostaHiripis/dataProcessing/src/main/resources/schema/agriculture/agriculture_test.xml
<?xml version='1.0' encoding='utf-8'?>
<agriculture
        xmlns="https://www.w3schools.com"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://www.w3schools.com agriculture_schema.xsd">

        <areaCode>2</areaCode>
        <area>Afghanistan</area>
        <itemCode>221</itemCode>
        <item>Almonds, with shell</item>
        <elementCode>5312</elementCode>
        <element>Area harvested</element>
        <year>1975</year>
        <unit>ha</unit>
        <value>0</value>
        <flag>F</flag>
</agriculture>
